### PR TITLE
Updated tracking code. Updated fork with upstream

### PR DESCRIPTION
**Pull request by scrofungulus**

### CODE REVIEW

**Comment by byerc** [comment]
Hubspot has updated their tracking script. Everything else seems to be the same, so I don't think any further changes need to be made. 
 
**Their documentation**
_Overview of Tracking API_
https://developers.hubspot.com/docs/methods/tracking_code_api/tracking_code_overview
_Tack Page View_
https://developers.hubspot.com/docs/methods/tracking_code_api/track_page_view
_Identify_
https://developers.hubspot.com/docs/methods/tracking_code_api/identify_visitor
_Track Event_
https://developers.hubspot.com/docs/methods/tracking_code_api/javascript_events_api

**Comment by beckysteele** [comment]
@byerc Did this ever get reviewed? If so, was there something found to be wrong with it? If not...

@bonominijl who on the team should review/approve PRs in the astronomer-integrations org? We had a system in place where no new Clickstream integration PRs could be merged without approval from someone with write access in this repo (still includes me). This one is ready to merge in, from my perspective, and could be used to validate and close a support issue.

**Comment by bonominijl** [comment]
@beckysteele  Collen is out until tomorrow, if this is urgent we can have @tedmiston take a look. For now I think it makes sense to assign Taylor to review and approve clickstream destination PRs

**Comment by beckysteele** [comment]
Thanks @bonominijl!

Hey @tedmiston! The background on this one: customer reported issue with Hubspot tracking pixel not firing using our integration, Collen looked into it and determined that Hubspot had changed the format of their tracking code, he made changes to the integration itself and issued this PR for review.

Upon merging of this PR, I'd recommend the v2 UI be changed to reflect the new fields (change `.option('portalId')` to `.option('trackingCode')`, remove API key option entirely).

**Comment by beckysteele** [comment]
@tedmiston, thank you for being so thorough! You brought up several great points, and I want to make sure we're using everybody's time effectively while getting to the true root cause of the problem.

@bonominijl, I'll message you directly on this, but the tl;dr version is maybe we should revisit the nature of the customer issue with a fresh perspective since this has been an open PR for so long. Would that be alright?  If so, who would you like to have revisit the (Hubspot tracking pixel not firing in staging app for a customer)?

**Comment by byerc** [comment]
I re-synched their upstream and made sure all tests are passing. @tedmiston 

For a new deploy we need to: 
- Bump the Hubspot version in analytics.js 
- Cut a new release of analytics.js
- Update the builder to the latest version of analytics.js and tag a new release 
- Deploy the builder in DC/OS
- Trigger a new analytics.js build for whoever is using Hubspot. 

Segment is still using Hubspot's older way of tracking it seems which I assume isn't an issue. I can't guarantee that this is going to resolve the current issues that are happening, but being caught up with Segment seems to be a solid first move.

**Comment by tedmiston** [comment]
Anyone know what the next action here is?  I'm not seeing any more comments after the two questions I asked above in October.  I think this might have been discussed offline but not super sure?

**Comment by bonominijl** [comment]
@tedmiston I don't know anything more beyond Collen's earlier comments. Can we see which customers are currently using the hubspot destination?

**Pull request closed without merging**
